erDiagram
    categoria{
    id int pk
    name_cat varchar(200)
    descripcion varchar(500)
    }

    producto{
    id int pk
    name_prod varchar(200)
    cod_prod varchar(50)
    precio decimal
    stock int
    id_cat int fk
    }

    cliente{
    id int pk
    nombre varchar(100)
    apellido varchar(100)
    email varchar(100)
    cedula varchar(10)
    }

    venta{
    id int fk
    id_producto int
    id_cliente int
    cantidad int
    }

    categoria ||--o{ producto:id_cat
    cliente ||--o{ venta:id_cliente
    producto ||--o{ venta:id_producto